#ifndef TinyML_int8_datahead
#define TinyML_int8_datahead

extern const unsigned char _Users_hemant_Downloads_custom_cnn_model_quantized_tflite[];
extern const int _Users_hemant_Downloads_custom_cnn_model_quantized_tflite_len;

#endif